service: alquant-swe-takehome-exercise

frameworkVersion: '3'

custom:
  wsgi:
    app: server.app.app
    pythonBin: python3
  pythonRequirements:
    zip: true
    dockerizePip: true
    useStaticCache: false

provider:
  name: aws
  runtime: python3.9
  region: eu-central-1
  deploymentMethod: direct

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
